spring:
  cloud:
#    circuit breaker:
#      resilience4j:
#        enabled: true
    gateway:
      routes:
        - id: auth_service
          uri: http://localhost:8081
          predicates:
            - Path=/api/v1/auth/**

        - id: user_service
          uri: http://localhost:8081
          predicates:
            - Path=/api/v1/users/**

        - id: post_service
          uri: http://localhost:8082
          predicates:
            - Path=/api/v1/posts/**

        - id: comment_service
          uri: http://localhost:8082
          predicates:
            - Path=/api/v1/comments/**

        - id: follow_service
          uri: http://localhost:8082
          predicates:
            - Path=/api/v1/follow/**

        - id: newsfeed_service
          uri: http://localhost:8083
          predicates:
            - Path=/api/v1/newsfeed
            - Path=/api/v1/news

server:
  port: 9000

logging:
  level:
    org:
      springframework:
        cloud:
          gateway: TRACE